/******************************************************************************/
/****            Generated by IBExpert 2007-03-31 ¿ÀÈÄ 4:08:49             ****/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES NONE;



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/



CREATE TABLE TB_SHOPORDER (
    SHOPID        VARCHAR(10) NOT NULL,
    ORDERID       INTEGER NOT NULL,
    USERNAME      VARCHAR(20),
    USERNAME_ENG  VARCHAR(20),
    USEREMAIL     VARCHAR(50),
    USERPHONE     VARCHAR(20),
    ISCOMPANY     SMALLINT DEFAULT 0 NOT NULL,
    COMPANY       VARCHAR(30),
    COMPANY_ENG   VARCHAR(30),
    COMPANYNO     VARCHAR(20),
    HOMEPAGE      VARCHAR(40),
    REGDATE       TIMESTAMP
);




/******************************************************************************/
/****                             Primary Keys                             ****/
/******************************************************************************/

ALTER TABLE TB_SHOPORDER ADD CONSTRAINT PK_TB_SHOPORDER PRIMARY KEY (SHOPID, ORDERID);


/******************************************************************************/
/****                             Foreign Keys                             ****/
/******************************************************************************/

ALTER TABLE TB_SHOPORDER ADD CONSTRAINT FK_TB_SHOPORDER_1 FOREIGN KEY (SHOPID) REFERENCES TB_SHOP (SHOPID);


/******************************************************************************/
/****                              Privileges                              ****/
/******************************************************************************/

