/******************************************************************************/
/****            Generated by IBExpert 2007-03-31 ¿ÀÈÄ 4:09:06             ****/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES NONE;



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/



CREATE TABLE TB_SHOPORDERITEM (
    SHOPID    VARCHAR(10) NOT NULL,
    ORDERID   INTEGER NOT NULL,
    ITEMID    INTEGER NOT NULL,
    ORDERCNT  INTEGER
);




/******************************************************************************/
/****                             Primary Keys                             ****/
/******************************************************************************/

ALTER TABLE TB_SHOPORDERITEM ADD CONSTRAINT PK_TB_SHOPORDERITEM PRIMARY KEY (SHOPID, ORDERID, ITEMID);


/******************************************************************************/
/****                             Foreign Keys                             ****/
/******************************************************************************/

ALTER TABLE TB_SHOPORDERITEM ADD CONSTRAINT FK_TB_SHOPORDERITEM_1 FOREIGN KEY (SHOPID, ORDERID) REFERENCES TB_SHOPORDER (SHOPID, ORDERID)
  USING INDEX FK_TB_SHOPORDERITEM_2;
ALTER TABLE TB_SHOPORDERITEM ADD CONSTRAINT FK_TB_SHOPORDERITEM_3 FOREIGN KEY (SHOPID, ITEMID) REFERENCES TB_SHOPITEM (SHOPID, ITEMID);


/******************************************************************************/
/****                              Privileges                              ****/
/******************************************************************************/

